name: "Publish Brrr to Cloudflare Pages"

on:
    workflow_dispatch:
    push: { branches: [ 'master' ] }

jobs:

    publish:
        runs-on: ubuntu-latest

        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        permissions:
            contents: read
            deployments: write

        defaults: { run: { shell: bash } }

        steps:

        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Setup Deno
            uses: denoland/setup-deno@v1

        -   name: Build Brrr
            run: deno task build

        -   name: Setup pnpm
            uses: pnpm/action-setup@v4
            with: { version: latest , run_install: false }

        -   name: Setup Wrangler
            uses: cloudflare/wrangler-action@v3
            with:
                packageManager: pnpm
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                wranglerVersion: 3
                command: |
                    pages deploy --project-name="brrr" --branch main --commit-dirty=true "_site"